version: '3'
services:
  frontend:
    build: Trash_Bin/
    ports: 
      - 5173:8080
  backend: 
    build: Database/
    ports: 
      - 18080:8080
    volumes:
      - ./Database/data:/usr/share/data